- hosts: tower
  gather_facts: no
  collections:
   - ansible.tower

  tasks:
  - name: Create a new organization
    tower_organization:
      name: "TestORG"
      description: "test org"
      state: present
